### ISSUE TITLE
How to implement permessage-deflate support

### ISSUE THREAD

**Issue by Asmod4n** [tatsuhiro-t/wslay#24]
I am a bit confused as to how implement deflate support, "permessage" lets one assume its for a complete message, but aparently it's on a per frame basis.

Would this need changes to wslay?

**Comment by jirihnidek** [comment]
First of all: you need not to add support to DEFLATE. IMHO only Google Chrome has experimental support for this WebSocket extension. When this extension is not negotiated, then web client nor web server doesn't use it.

Related information can be found in RFC. ATM there is only draft for this RFC: https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-27.

I guess that it will require some changes in wslay, because bit RSV1 from WebSocket header is used for indication of message compression.
